
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kebria Zaman
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    String userID;
    public UserProfile() {
        initComponents();
    }

    public UserProfile(String id)
    {
        userID = id;
        initComponents();
        
        assignData();
    }
    public void assignData()
    {
        try
            {              
            BufferedReader br = new BufferedReader(new FileReader("/Users/sandeshkey/Desktop/Courier Service System/Files/Accounts.txt"));
            String s;
            b:
            while((s=br.readLine()) != null)
            {
                if(s.equals(userID))
                {
                    txtID.setText(s);
                    txtFirstName.setText(br.readLine());
                    txtLastName.setText(br.readLine());
                    txtMail.setText(br.readLine());
                    txtPass.setText(br.readLine());
                    txtCur.setText(br.readLine());
                    txtPer.setText(br.readLine());
                    break b;
                }
            }
            }catch(Exception ex)
            {
                 ex.printStackTrace();
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCur = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        imagelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(440, 100));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(40, 43, 44));
        jLabel2.setFont(new java.awt.Font("MADE TOMMY", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 220, 220));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER PROFILE");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 50));

        jLabel4.setBackground(new java.awt.Color(40, 43, 44));
        jLabel4.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(200, 200, 200));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 30));

        jLabel5.setBackground(new java.awt.Color(40, 43, 44));
        jLabel5.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(200, 200, 200));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email ID");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 30));

        jLabel6.setBackground(new java.awt.Color(40, 43, 44));
        jLabel6.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(200, 200, 200));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 30));

        jLabel7.setBackground(new java.awt.Color(40, 43, 44));
        jLabel7.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(200, 200, 200));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Current Address");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, 30));

        jLabel8.setBackground(new java.awt.Color(40, 43, 44));
        jLabel8.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(200, 200, 200));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Employee ID");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jLabel9.setBackground(new java.awt.Color(40, 43, 44));
        jLabel9.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(200, 200, 200));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("First Name");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 30));

        txtID.setEnabled(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, 30));
        jPanel1.add(txtPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 230, 30));

        jLabel10.setBackground(new java.awt.Color(40, 43, 44));
        jLabel10.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(200, 200, 200));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Permanent Address");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 30));
        jPanel1.add(txtCur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 230, 30));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, 30));
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 230, 30));
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 230, 30));
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, 30));

        deleteBtn.setBackground(new java.awt.Color(40, 43, 44));
        deleteBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.setBorderPainted(false);
        deleteBtn.setDefaultCapable(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 90, 40));

        exitBtn.setBackground(new java.awt.Color(40, 43, 44));
        exitBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(null);
        exitBtn.setBorderPainted(false);
        exitBtn.setDefaultCapable(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 90, 40));

        updateBtn.setBackground(new java.awt.Color(40, 43, 44));
        updateBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(null);
        updateBtn.setBorderPainted(false);
        updateBtn.setDefaultCapable(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 40));

        imagelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picUssr.png"))); // NOI18N
        jPanel1.add(imagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed


        

        ArrayList<String> dataList = new ArrayList<String>();
        
        
        
            if ( txtFirstName.getText().equals("") || txtLastName.getText().equals("") || txtMail.getText().equals("") || txtPass.getText().equals("") || txtCur.getText().equals("") || txtPer.getText().equals("") )
            {
                JOptionPane.showMessageDialog(this, "Fill all the fields");
            }

            else
            {
            try
            {
                
    
            BufferedReader br = new BufferedReader(new FileReader("/Users/sandeshkey/Desktop/Courier Service System/Files/Accounts.txt"));
            String s;
            
           
            while((s=br.readLine()) != null)
            {
  
               dataList.add(s);
           
            }
                b: 
                for (int i = 0; i < dataList.size(); i++)
                {
                    if(dataList.get(i).equals(txtID.getText()))
                    {
                        dataList.set(i+1, txtFirstName.getText());
                        dataList.set(i+2, txtLastName.getText());
                        dataList.set(i+3, txtMail.getText());
                        dataList.set(i+4, txtPass.getText());
                        dataList.set(i+5, txtCur.getText());
                        dataList.set(i+6, txtPer.getText());
                        
                        break b;
                    }
                }
                for (int i = 0; i < dataList.size(); i++) {
                    if(i==6)
                    {
                        dataList.add(" ");
                    }
                }
            
            br.close();
            
            
            
            
            
            FileWriter writer = new FileWriter("/Users/sandeshkey/Desktop/Courier Service System/Files/Accounts.txt");
            
            for (int i = 0; i < dataList.size(); i++)
                {
                    writer.write(dataList.get(i)+"\n");
                    
                }
                
                writer.close();
                JOptionPane.showMessageDialog(this, "Data is successfully updated");
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
            
            }
        
            
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        
        ArrayList<String> dataList = new ArrayList<String>();
        
        
            
            try
            {
                
    
            BufferedReader br = new BufferedReader(new FileReader("/Users/sandeshkey/Desktop/Courier Service System/Files/Accounts.txt"));
            String s;
           
            while((s=br.readLine()) != null)
            {
                if(s.equals(txtID.getText()))
                {
                    for (int i = 0; i < 6; i++)
                    {
                        br.readLine();
                    }
                }
                
               dataList.add(s);
            }
                b:
                for (int i = 0; i < dataList.size(); i++)
                {
                    if(dataList.get(i).equals(txtID.getText()))
                    {
                        dataList.remove(i);
                        break b;
                    }
                }
            
            br.close();
            
            FileWriter writer = new FileWriter("/Users/sandeshkey/Desktop/Courier Service System/Files/Accounts.txt");
            
            for (int i = 0; i < dataList.size(); i++)
                {
                    writer.write(dataList.get(i)+"\n");
                }
                
                writer.close();
                
                JOptionPane.showMessageDialog(this, "Data is deleted successfully");
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
          
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed


        
        this.dispose();
        
        
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel imagelbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCur;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPer;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
