/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Course_ID]
      ,[Course_Name]
      ,[Course_content]
      ,[Course_Price]
      ,[Lecturer_Name]
      ,[Class_Duration]
      ,[Course_Image]
      ,[Added_by]
  FROM [User].[dbo].[Course]