/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Name]
      ,[Email]
      ,[Username]
      ,[Course_Name]
      ,[Cardholder_Name]
      ,[Card_Number]
      ,[ExpMonth]
      ,[ExpYear_Duration]
      ,[CVV]
  FROM [User].[dbo].[Enroll]